version: '3.9'
services:
  backend:
    build:
      context: ./RPG project NPC generator
    ports:
      - "7017:80"
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - RPG project NPC generator
      - frontend
